PIA_WheelDeal/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PIA_WheelDeal.Models;
using System.Diagnostics;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.Rendering;

using PIA_WheelDeal.Models.dbModels;
using Microsoft.AspNetCore.Authorization;
namespace PIA_WheelDeal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
		private readonly BaseDeGatosContext _context;

		public HomeController(ILogger<HomeController> logger, BaseDeGatosContext context)
        {
			_logger = logger;
			_context = context;

		}

		// GET: Vehiculoes
		public async Task<IActionResult> IndexAsync()
		{
			var baseDeGatosContext = _context.Vehiculos.Include(v => v.IdTipoNavigation);
			return View(await baseDeGatosContext.ToListAsync());
		}

        //Vista sin restricciones
		public IActionResult Acercade()
        {
            return View();
        }

        // Vista exclusiva de acceso para el ADMIN
        [Authorize (Roles = "Admin")]
        public IActionResult Gerencia()
        {
            return View();
        }
		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }


    }
}

PIA_WheelDeal/Controllers/PeticionesController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PIA_WheelDeal.Models.dbModels;
using PIA_WheelDeal.Models.DTO;
using PIA_WheelDeal.Models.ViewModels;

namespace PIA_WheelDeal.Controllers
{
	[Authorize]
	public class PeticionesController : Controller
    {
        private readonly BaseDeGatosContext _context;
        public PeticionesController(BaseDeGatosContext context)
        {
            _context = context;
        }



        //GETEAR LOS PARAMETROS DEL VEHICULO SELECCIONADO
        public async Task<IActionResult> Index(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var vehiculo = await _context.Vehiculos
                .Include(v => v.IdTipoNavigation)
                .FirstOrDefaultAsync(m => m.IdProd == id);
            if (vehiculo == null)
            {
                return NotFound();
            }
            PeticionViewmodel peticion2 = new PeticionViewmodel()
            {
                Peticion = new PeticionCompraDTO()
                {
                    IdProd = vehiculo.IdProd,

                },

                Producto = new VehiculoDTO()
                {
                    Nombre = vehiculo.Nombre,
                    Precio = vehiculo.Precio,
                    Matricula = vehiculo.Matricula,
                    Descripcion = vehiculo.Descripcion,
                    Img = vehiculo.Img
                }
            };
            return View(peticion2);
        }

        // POST: PeticionCompras/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PeticionCompraDTO peticion)
        {
            if (ModelState.IsValid)
            {
                if (int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out int currentuserid))
                {
					PeticionCompra peticion1 = new PeticionCompra()
                    {
                        IdInd = currentuserid,
                        IdProd = peticion.IdProd,
                        IdStatus = 1,
                        Fecha = DateTime.Now

					};
                    
                    _context.Add(peticion1);
					await _context.SaveChangesAsync();
					return RedirectToAction("Index", "Home");
				}
                
            }
            return BadRequest();
        }
    }
}

PIA_WheelDeal/Controllers/VehiculoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PIA_WheelDeal.Models.dbModels;
using PIA_WheelDeal.Models.DTO;

namespace PIA_WheelDeal.Controllers
{
    //Controlador Exclusivo de Admins
    [Authorize(Roles = "Admin")]
    public class VehiculoesController : Controller
    {
        private readonly BaseDeGatosContext _context;

        public VehiculoesController(BaseDeGatosContext context)
        {
            _context = context;
        }

        // GET: Vehiculoes
        public async Task<IActionResult> Index()
        {
            var baseDeGatosContext = _context.Vehiculos.Include(v => v.IdTipoNavigation);
            return View(await baseDeGatosContext.ToListAsync());
        }

        // GET: Vehiculoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculos
                .Include(v => v.IdTipoNavigation)
                .FirstOrDefaultAsync(m => m.IdProd == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

		// GET: Vehiculoes/Create
		public IActionResult Create()
		{
			VehiculoDTO vehiculotipo = new VehiculoDTO
			{
				TiposCatalogo = new SelectList(_context.TiposCatalogos, "IdTipo", "Tipo")
			};
			return View(vehiculotipo);
		}

		// POST: Vehiculoes/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VehiculoDTO vehiculo)
        {
            if (ModelState.IsValid)
            {
				Vehiculo vehiculo1 = new Vehiculo
				{
					Nombre = vehiculo.Nombre,
					IdTipo = vehiculo.IdTipo,
					Precio = vehiculo.Precio,
					Matricula = vehiculo.Matricula,
					Descripcion = vehiculo.Descripcion,
					Disponible = vehiculo.Disponible,
                    Img = vehiculo.Img
				};
				_context.Add(vehiculo1);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
			vehiculo.TiposCatalogo = new SelectList(_context.TiposCatalogos, "IdTipo", "Tipo", vehiculo.IdTipo);
			return View(vehiculo);
		}

        // GET: Vehiculoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculos.FindAsync(id);
            if (vehiculo == null)
            {
                return NotFound();
            }
            ViewData["IdTipo"] = new SelectList(_context.TiposCatalogos, "IdTipo", "IdTipo", vehiculo.IdTipo);
            return View(vehiculo);
        }

        // POST: Vehiculoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, VehiculoDTO vehiculo)
        {
            if (id != vehiculo.IdProd)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
				Vehiculo vehiculo2 = new Vehiculo
				{
					IdProd = vehiculo.IdProd,
					Nombre = vehiculo.Nombre,
					IdTipo = vehiculo.IdTipo,
					Precio = vehiculo.Precio,
					Matricula = vehiculo.Matricula,
					Descripcion = vehiculo.Descripcion,
					Disponible = vehiculo.Disponible,
                    Img = vehiculo.Img
                };

				try
                {
                    _context.Update(vehiculo2);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiculoExists(vehiculo.IdProd))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdTipo"] = new SelectList(_context.TiposCatalogos, "IdTipo", "IdTipo", vehiculo.IdTipo);
            return View(vehiculo);
        }

        // GET: Vehiculoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehiculo = await _context.Vehiculos
                .Include(v => v.IdTipoNavigation)
                .FirstOrDefaultAsync(m => m.IdProd == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

        // POST: Vehiculoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehiculo = await _context.Vehiculos.FindAsync(id);
            if (vehiculo != null)
            {
                _context.Vehiculos.Remove(vehiculo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehiculoExists(int id)
        {
            return _context.Vehiculos.Any(e => e.IdProd == id);
        }
    }
}

PIA_WheelDeal/Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PIA_WheelDeal.Models.dbModels;

namespace PIA_WheelDeal.Controllers
{
    public class VentasController : Controller
    {
        private readonly BaseDeGatosContext _context;

        public VentasController(BaseDeGatosContext context)
        {
            _context = context;
        }

        // GET: Ventas
        public async Task<IActionResult> Index()
        {
            var baseDeGatosContext = _context.Ventas.Include(v => v.IdIndNavigation).Include(v => v.IdProdNavigation);
            return View(await baseDeGatosContext.ToListAsync());
        }

        // GET: Ventas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas
                .Include(v => v.IdIndNavigation)
                .Include(v => v.IdProdNavigation)
                .FirstOrDefaultAsync(m => m.IdIngreso == id);
            if (venta == null)
            {
                return NotFound();
            }

            return View(venta);
        }

        // GET: Ventas/Create
        public IActionResult Create()
        {
            ViewData["IdInd"] = new SelectList(_context.Users, "Id", "Id");
            ViewData["IdProd"] = new SelectList(_context.Vehiculos, "IdProd", "IdProd");
            return View();
        }

        // POST: Ventas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdIngreso,IdInd,IdProd,Monto,Descripcion,Fecha")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdInd"] = new SelectList(_context.Users, "Id", "Id", venta.IdInd);
            ViewData["IdProd"] = new SelectList(_context.Vehiculos, "IdProd", "IdProd", venta.IdProd);
            return View(venta);
        }

        // GET: Ventas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas.FindAsync(id);
            if (venta == null)
            {
                return NotFound();
            }
            ViewData["IdInd"] = new SelectList(_context.Users, "Id", "Id", venta.IdInd);
            ViewData["IdProd"] = new SelectList(_context.Vehiculos, "IdProd", "IdProd", venta.IdProd);
            return View(venta);
        }

        // POST: Ventas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdIngreso,IdInd,IdProd,Monto,Descripcion,Fecha")] Venta venta)
        {
            if (id != venta.IdIngreso)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venta);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VentaExists(venta.IdIngreso))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdInd"] = new SelectList(_context.Users, "Id", "Id", venta.IdInd);
            ViewData["IdProd"] = new SelectList(_context.Vehiculos, "IdProd", "IdProd", venta.IdProd);
            return View(venta);
        }

        // GET: Ventas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venta = await _context.Ventas
                .Include(v => v.IdIndNavigation)
                .Include(v => v.IdProdNavigation)
                .FirstOrDefaultAsync(m => m.IdIngreso == id);
            if (venta == null)
            {
                return NotFound();
            }

            return View(venta);
        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venta = await _context.Ventas.FindAsync(id);
            if (venta != null)
            {
                _context.Ventas.Remove(venta);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VentaExists(int id)
        {
            return _context.Ventas.Any(e => e.IdIngreso == id);
        }
    }
}

PIA_WheelDeal/Views/Home/Acercade.cshtml
@{
    ViewData["Title"] = "Administración";
}

@* SECCION CON LOS JAVASCRIPT QUE USARÁ ESTA VISTA *@
@section Scripts {
    <script>
        $("#contenedorprincipal").addClass("container").removeClass("container-fluid")
    </script>
}

@* SECCION CON LOS ESTILOS QUE USARÁ ESTA VISTA *@
@section Styles {
    <link rel="stylesheet" href="~/css/acercade.css" asp-append-version="true" />
}

<div class="row text-center" id="">
    <div class="col pt-5">
        <h3 class="border border-dark border-5">Acerca de Nosotros</h3>
    </div>
    
</div>
<div class="row text-center rounded bg-dark border border-5">
    <div class="col centradito">
        <p>
            En WheelDeal, nos apasiona el mundo automotriz.
            Desde nuestra fundación en 1992, nos hemos dedicado a
            ofrecer a nuestros clientes vehículos de la más alta calidad,
            combinando tecnología avanzada, diseño innovador y un servicio al cliente excepcional.
            Nos esforzamos por ser más que una simple concesionaria;
            queremos ser tu socio de confianza en cada paso del camino hacia la adquisición del automóvil de tus sueños.
        </p>
    </div>
</div>

<div class="row text-center pt-5">
    <div class="col pt-5">
        <h3 class="border border-dark border-5">Misión</h3>
    </div>
</div>
<div class="row text-center rounded bg-dark border border-5">
    <div class="col centradito">
        <p>
            Nuestra misión es proporcionar a nuestros clientes una experiencia automotriz inigualable,
            ofreciendo una amplia selección de vehículos que se adapten a las necesidades y deseos de cada persona.
            Nos comprometemos a brindar un servicio personalizado, asesoría experta y soluciones financieras accesibles
            para que cada cliente pueda disfrutar del automóvil perfecto con total tranquilidad y satisfacción.
        </p>
    </div>
</div>


<div class="row text-center pt-5">
    <div class="col">
        <h3 class="border border-dark border-5">Visión</h>
    </div>
</div>
<div class="row text-center rounded bg-dark border border-5">
    <div class="col centradito">
        <p>
            Nuestra visión es ser líderes en el mercado automotriz,
            reconocidos por nuestra integridad, innovación y excelencia
            en el servicio al cliente. Aspiramos a expandir nuestra presencia,
            adoptando tecnologías sostenibles y prácticas comerciales responsables que
            contribuyan al bienestar de nuestras comunidades y al cuidado del medio ambiente.
            Queremos ser el referente de confianza donde cada cliente encuentre no solo un vehículo, sino una experiencia extraordinaria.
        </p>
    </div>
</div>

PIA_WheelDeal/Views/Home/Gerencia.cshtml
@{
    ViewData["Title"] = "Gerencia";
}
<p><a asp-controller="Vehiculoes" asp-action="Index">Inventario</a></p>
<p><a asp-controller="ApplicationUsers" asp-action="Index">Usuarios</a></p>
<p><a asp-controller="TiposCatalogo" asp-action="Index">Administrar Tipos de carro</a></p>
<p><a asp-controller="StatusCatalogo" asp-action="Index">Administrar Tipos de estados</a></p>

PIA_WheelDeal/Views/Home/Index.cshtml
@model IEnumerable<PIA_WheelDeal.Models.dbModels.Vehiculo>

@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@* SECCION CON LAS FUNCIONES DE ESTA VISTA *@
@functions{
		public async Task<bool> IsInRoleAsync(string role)
		{
			var user = await UserManager.GetUserAsync(User);
			return user != null && await UserManager.IsInRoleAsync(user, role);
		}
}
@* SECCION CON LOS JAVASCRIPT QUE USARÁ ESTA VISTA *@
@section Scripts {
	<script>

		

	</script>
}
@* SECCION CON LOS ESTILOS QUE USARÁ ESTA VISTA *@
@section Styles{
	<link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />
}


<div class="row">
	<div class="col-xl-2 col-lg-3 col-4 bg-dark text-warning">
		<div><!--Primera seccion-->
			<div class="row bg-warning text-dark border border-3 border-dark">
				<h5>Cuenta</h5>
			</div>
			<div class="row p-0 bg-dark text-white">
				<partial name="_LoginPartial"/>
			</div>
		</div>
		@if (await IsInRoleAsync("ADMIN"))
		{
			<div id="validador">
				<!--Segunda Seccion, esta seccion tendrá una validacion si Rol=ADMIN-->
				<div class="row bg-warning text-dark border border-3 border-dark">
					<h5>Administracion</h5>
				</div>
				<div class="row p-0 bg-dark text-white">
					<ul>
						
						<li class="pt-2 pb-2 mb-1 border border-3 border-warning text-center rounded">
							<a class="btn btn-dark w-100" asp-controller="PeticionCompras" asp-action="Index">Solicitudes</a>
						</li>
						<li class="pt-2 pb-2 mb-1 border border-3 border-warning text-center rounded">
							<a class="btn btn-dark w-100" asp-controller="Ventas" asp-action="Index">Ventas</a>
						</li>
						<li class="pt-2 pb-2 mb-1 border border-3 border-warning text-center rounded">
							<a class="btn btn-dark w-100" asp-controller="Home" asp-action="Gerencia">Gerencia</a>
						</li>
					</ul>
				</div>
			</div>
		}
		
    </div>
	<!--Fin de las secciones-->
	<!--Columna con todos los productos-->
	<div class="col-xl-10 col-lg-9 col-8 border border-primary">
		<div class="row" id="productosdisplay"><!--Display que displayeara todos los productos,
		cada columna es un producto, las columnas tienen un breakpoint de 4 por lo
		que dará la ilusion de ser una triple fila hacia abajo-->
			@foreach (var item in Model)
			{
				@if(item.Disponible==true){
					<div class="col-4 pt-4">
							<div class="card" style="width: 30rem; height: 100%;">
							<img src="@Html.DisplayFor(modelItem => item.Img)" class="card-img-top" alt="...">
								<div class="card-body">
									<h5 class="card-title"><strong>@Html.DisplayFor(modelItem => item.Nombre)</strong></h5>
									<p class="card-text"><strong>$@Html.DisplayFor(modelItem => item.Precio)</strong></p>
									<p class="card-text"><strong>@Html.DisplayFor(modelItem => item.IdTipoNavigation.Tipo)</strong></p>
									<p class="card-text">Matricula: @Html.DisplayFor(modelItem => item.Matricula)</p>
									<p class="card-text">@Html.DisplayFor(modelItem => item.Descripcion)</p>
									<a class="btn btn-dark compra" asp-controller="Peticiones" asp-action="Index" asp-route-id="@item.IdProd">Comprar</a>
								</div>
							</div>
						</div>
				}
			}
		</div>
	</div>
</div>